name: ci-build

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine-version:
          - 3.16
          - 3.17
          - 3.18
          - 3.19
          - 3.20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set version tag
        id: extract_version
        run: echo "VERSION=1.0.0" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build build
        working-directory: alpine-${{ matrix.alpine-version }}
        run: docker build --progress=plain --platform=amd64 --tag "ghcr.io/wilsonify/alpine-stack-${{ matrix.alpine-version }}-build:${{ env.VERSION }}" -f Dockerfile-build .

      - name: Push build
        run: docker push "ghcr.io/wilsonify/alpine-stack-${{ matrix.alpine-version }}-build:${{ env.VERSION }}"
